# Name of the GitHub Actions workflow
name: Playwright Github Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  demoqa-smoke:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install node js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Chrome browser for Playwright
        run: pnpm exec playwright install chrome

      - name: Run demoqa smoke tests
        run: pnpm run test:serial:ci
        env:
          ENV: "qa"
          CI: true

      - name: Wait for job completion
        run: sleep 10s
        if: always()

      - name: Check if HTML report exists
        run: |
          if [ -d "html-report" ]; then
            echo "HTML report exists."
          else
            echo "HTML report does not exist. Exiting..."
            exit 1
          fi
        if: always()

      - name: Zip HTML report
        run: zip -r html-report-demoqa.zip html-report
        if: always()

      - name: Upload demoqa artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-report-demoqa
          path: html-report-demoqa.zip
          if-no-files-found: error
        if: always()

      - name: Generate artifact link
        id: artifact_link
        run: echo "artifact_url=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_OUTPUT
        if: always()

      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: "#playwright-test-reports"
          SLACK_USERNAME: Playwright GitHub Actions
          SLACK_MESSAGE: "Demoqa smoke results: [Artifacts](${{ steps.artifact_link.outputs.artifact_url }})"
        if: always()

  tc-platform-smoke:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install node js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Chrome browser for Playwright
        run: pnpm exec playwright install chrome

      - name: Run tc-platform smoke tests
        run: pnpm run test:tc-platform:ci
        env:
          ENV: "tcQa"
          CI: true
          TC_USER_USERNAME: ${{ secrets.TC_USER_USERNAME }}
          TC_USER_PASSWORD: ${{ secrets.TC_USER_PASSWORD }}
          TC_ADMIN_USERNAME: ${{ secrets.TC_ADMIN_USERNAME }}
          TC_ADMIN_PASSWORD: ${{ secrets.TC_ADMIN_PASSWORD }}
          TC_PARTNER_USERNAME: ${{ secrets.TC_PARTNER_USERNAME }}
          TC_PARTNER_PASSWORD: ${{ secrets.TC_PARTNER_PASSWORD }}

      - name: Zip HTML report
        run: zip -r html-report-tc-platform.zip html-report
        if: always()

      - name: Upload tc-platform artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-report-tc-platform
          path: html-report-tc-platform.zip
          if-no-files-found: error
        if: always()
